name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Debug directory contents
      run: |
        ls -R
        echo "Working Directory: $PWD"
    - name: setup
      run: bash setup.sh
      working-directory: src
      continue-on-error: true
    - name: Deploy Azure resources
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az ml job create \
          --file $GITHUB_WORKSPACE/src/job.yml \
          --workspace-name aml-pipelinecli-dev
