name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Directory oath 
      run: |
        cd /home/runner/work/Azure-MLops/src
        pwd
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Upload AML job configuration
      run: az ml job create --file job.yml --workspace-name aml-pipelinecli-dev --resource-group mlops-pipelinecli-rg

